version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - "8081:8081"
      - "8080:8080"

  identitiyservice:
    container_name: identitiyservice
    image: ${DOCKER_REGISTRY-}identitiyservice
    build:
      context: .
      dockerfile: src/IdentitiyService/Dockerfile
    environment:
      Database__Host: postgres-db
      Database__DbName: identities-db
      Database__UserName: test
      Database__Password: test

  postgres-db:
    container_name: "postgres-db"
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: identities-db
    ports:
      - "25432:5432"


  authorizationservice:
    image: ${DOCKER_REGISTRY-}authorizationservice
    build:
      context: .
      dockerfile: src/AuthorizationService/Dockerfile

